
## Local h2 db
#spring:
#  datasource:
#    url: jdbc:h2:mem:noqdb
#    username: noq_username
#    password: noq_password
#    driverClassName: org.h2.Driver
#  h2:
#    console.enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: update
#    show-sql: true

# Local docker db
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/noq_db
    username: root
    password: noq_password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update #change this
    show-sql: true
