## Local h2 db
#spring:
#  datasource:
#    url: jdbc:h2:mem:noqdb
#    username: noq_username
#    password: noq_password
#    driverClassName: org.h2.Driver
#  h2:
#    console.enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: update
#    show-sql: true

# Default Local db
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/noq_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:noq_password}
    driverClassName: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.MySQL5Dialect}
    hibernate.ddl-auto: ${DATABASE_DDL_AUTO:none}
    show-sql: ${DATABASE_SHOW_SQL:true}
