spring:
  datasource:
    url: jdbc:h2:mem:noqdb
    #url: jdbc:mysql://localhost:3600/noq_dq
    username: noq_username
    #username: root
    password: noq_password
    driverClassName: org.h2.Driver
    #driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    #hibernate.ddl-auto: none
    show-sql: true